all: false
dir: 'internal/repo'
filename: mocks_repo.go
force-file-write: false
formatter: goimports
log-level: info
structname: '{{.Mock}}{{.InterfaceName}}'
pkgname: 'repo'
recursive: false
require-template-schema-exists: true
template: testify
template-schema: '{{.Template}}.schema.json'
packages:
  pvz-service/internal/repo:
    interfaces:
      PvzRepo:
      ReceptionRepo:
      ProductRepo:
