version: "3.9"


x-db-environment: &x-db-environment
  POSTGRES_SSL_MODE: "disable"
  POSTGRES_HOST: "db"
  POSTGRES_PORT: "5432"
  POSTGRES_DB: "db"
  POSTGRES_PASSWORD: "postgrespasswd"
  POSTGRES_USER: "user"

x-backend-app-environment: &x-backend-app-environment
  GOMAXPROCS: "1"
  # App
  APP_NAME: "pvz-service"
  APP_VERSION: "1.0.0"
  # HTTP settings
  HTTP_PORT: "8080"
  # Logger
  LOG_LEVEL: "debug"
  # PG
  PG_POOL_MAX: "25"
  PG_URL: "postgres://user:postgrespasswd@db:5432/db"

services:
  db:
    container_name: db
    image: postgres:17-alpine
    environment:
      <<: *x-db-environment
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      app_network:
        aliases:
          - db.lvh.me

  app:
    container_name: app
    platform: linux/amd64
    pid: "host"
    build:
      context: .
    environment:
      <<: *x-backend-app-environment
    ports:
      - "8080:8080"
    depends_on:
      - db
    networks:
      app_network:
        aliases:
          - app.lvh.me

networks:
  app_network:
    external: false


volumes:
  db_data: