// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package usecase

import (
	"context"
	"pvz-service/internal/entity"
	"time"

	mock "github.com/stretchr/testify/mock"
)

// NewMockPvzRepo creates a new instance of MockPvzRepo. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockPvzRepo(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockPvzRepo {
	mock := &MockPvzRepo{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockPvzRepo is an autogenerated mock type for the PvzRepo type
type MockPvzRepo struct {
	mock.Mock
}

type MockPvzRepo_Expecter struct {
	mock *mock.Mock
}

func (_m *MockPvzRepo) EXPECT() *MockPvzRepo_Expecter {
	return &MockPvzRepo_Expecter{mock: &_m.Mock}
}

// Create provides a mock function for the type MockPvzRepo
func (_mock *MockPvzRepo) Create(ctx context.Context, pvz entity.Pvz) (*entity.Pvz, error) {
	ret := _mock.Called(ctx, pvz)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 *entity.Pvz
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, entity.Pvz) (*entity.Pvz, error)); ok {
		return returnFunc(ctx, pvz)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, entity.Pvz) *entity.Pvz); ok {
		r0 = returnFunc(ctx, pvz)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.Pvz)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, entity.Pvz) error); ok {
		r1 = returnFunc(ctx, pvz)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockPvzRepo_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockPvzRepo_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx
//   - pvz
func (_e *MockPvzRepo_Expecter) Create(ctx interface{}, pvz interface{}) *MockPvzRepo_Create_Call {
	return &MockPvzRepo_Create_Call{Call: _e.mock.On("Create", ctx, pvz)}
}

func (_c *MockPvzRepo_Create_Call) Run(run func(ctx context.Context, pvz entity.Pvz)) *MockPvzRepo_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(entity.Pvz))
	})
	return _c
}

func (_c *MockPvzRepo_Create_Call) Return(pvz1 *entity.Pvz, err error) *MockPvzRepo_Create_Call {
	_c.Call.Return(pvz1, err)
	return _c
}

func (_c *MockPvzRepo_Create_Call) RunAndReturn(run func(ctx context.Context, pvz entity.Pvz) (*entity.Pvz, error)) *MockPvzRepo_Create_Call {
	_c.Call.Return(run)
	return _c
}

// GetById provides a mock function for the type MockPvzRepo
func (_mock *MockPvzRepo) GetById(ctx context.Context, id string) (*entity.Pvz, error) {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetById")
	}

	var r0 *entity.Pvz
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*entity.Pvz, error)); ok {
		return returnFunc(ctx, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *entity.Pvz); ok {
		r0 = returnFunc(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.Pvz)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockPvzRepo_GetById_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetById'
type MockPvzRepo_GetById_Call struct {
	*mock.Call
}

// GetById is a helper method to define mock.On call
//   - ctx
//   - id
func (_e *MockPvzRepo_Expecter) GetById(ctx interface{}, id interface{}) *MockPvzRepo_GetById_Call {
	return &MockPvzRepo_GetById_Call{Call: _e.mock.On("GetById", ctx, id)}
}

func (_c *MockPvzRepo_GetById_Call) Run(run func(ctx context.Context, id string)) *MockPvzRepo_GetById_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockPvzRepo_GetById_Call) Return(pvz *entity.Pvz, err error) *MockPvzRepo_GetById_Call {
	_c.Call.Return(pvz, err)
	return _c
}

func (_c *MockPvzRepo_GetById_Call) RunAndReturn(run func(ctx context.Context, id string) (*entity.Pvz, error)) *MockPvzRepo_GetById_Call {
	_c.Call.Return(run)
	return _c
}

// GetByReceptionDate provides a mock function for the type MockPvzRepo
func (_mock *MockPvzRepo) GetByReceptionDate(ctx context.Context, startDate *time.Time, endDate *time.Time, limit int, offset int) ([]entity.Pvz, error) {
	ret := _mock.Called(ctx, startDate, endDate, limit, offset)

	if len(ret) == 0 {
		panic("no return value specified for GetByReceptionDate")
	}

	var r0 []entity.Pvz
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *time.Time, *time.Time, int, int) ([]entity.Pvz, error)); ok {
		return returnFunc(ctx, startDate, endDate, limit, offset)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *time.Time, *time.Time, int, int) []entity.Pvz); ok {
		r0 = returnFunc(ctx, startDate, endDate, limit, offset)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]entity.Pvz)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *time.Time, *time.Time, int, int) error); ok {
		r1 = returnFunc(ctx, startDate, endDate, limit, offset)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockPvzRepo_GetByReceptionDate_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByReceptionDate'
type MockPvzRepo_GetByReceptionDate_Call struct {
	*mock.Call
}

// GetByReceptionDate is a helper method to define mock.On call
//   - ctx
//   - startDate
//   - endDate
//   - limit
//   - offset
func (_e *MockPvzRepo_Expecter) GetByReceptionDate(ctx interface{}, startDate interface{}, endDate interface{}, limit interface{}, offset interface{}) *MockPvzRepo_GetByReceptionDate_Call {
	return &MockPvzRepo_GetByReceptionDate_Call{Call: _e.mock.On("GetByReceptionDate", ctx, startDate, endDate, limit, offset)}
}

func (_c *MockPvzRepo_GetByReceptionDate_Call) Run(run func(ctx context.Context, startDate *time.Time, endDate *time.Time, limit int, offset int)) *MockPvzRepo_GetByReceptionDate_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*time.Time), args[2].(*time.Time), args[3].(int), args[4].(int))
	})
	return _c
}

func (_c *MockPvzRepo_GetByReceptionDate_Call) Return(pvzs []entity.Pvz, err error) *MockPvzRepo_GetByReceptionDate_Call {
	_c.Call.Return(pvzs, err)
	return _c
}

func (_c *MockPvzRepo_GetByReceptionDate_Call) RunAndReturn(run func(ctx context.Context, startDate *time.Time, endDate *time.Time, limit int, offset int) ([]entity.Pvz, error)) *MockPvzRepo_GetByReceptionDate_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockReceptionRepo creates a new instance of MockReceptionRepo. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockReceptionRepo(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockReceptionRepo {
	mock := &MockReceptionRepo{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockReceptionRepo is an autogenerated mock type for the ReceptionRepo type
type MockReceptionRepo struct {
	mock.Mock
}

type MockReceptionRepo_Expecter struct {
	mock *mock.Mock
}

func (_m *MockReceptionRepo) EXPECT() *MockReceptionRepo_Expecter {
	return &MockReceptionRepo_Expecter{mock: &_m.Mock}
}

// Create provides a mock function for the type MockReceptionRepo
func (_mock *MockReceptionRepo) Create(ctx context.Context, pvzId string) (*entity.Reception, error) {
	ret := _mock.Called(ctx, pvzId)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 *entity.Reception
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*entity.Reception, error)); ok {
		return returnFunc(ctx, pvzId)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *entity.Reception); ok {
		r0 = returnFunc(ctx, pvzId)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.Reception)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, pvzId)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockReceptionRepo_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockReceptionRepo_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx
//   - pvzId
func (_e *MockReceptionRepo_Expecter) Create(ctx interface{}, pvzId interface{}) *MockReceptionRepo_Create_Call {
	return &MockReceptionRepo_Create_Call{Call: _e.mock.On("Create", ctx, pvzId)}
}

func (_c *MockReceptionRepo_Create_Call) Run(run func(ctx context.Context, pvzId string)) *MockReceptionRepo_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockReceptionRepo_Create_Call) Return(reception *entity.Reception, err error) *MockReceptionRepo_Create_Call {
	_c.Call.Return(reception, err)
	return _c
}

func (_c *MockReceptionRepo_Create_Call) RunAndReturn(run func(ctx context.Context, pvzId string) (*entity.Reception, error)) *MockReceptionRepo_Create_Call {
	_c.Call.Return(run)
	return _c
}

// GetById provides a mock function for the type MockReceptionRepo
func (_mock *MockReceptionRepo) GetById(ctx context.Context, id string) (*entity.Reception, error) {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetById")
	}

	var r0 *entity.Reception
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*entity.Reception, error)); ok {
		return returnFunc(ctx, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *entity.Reception); ok {
		r0 = returnFunc(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.Reception)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockReceptionRepo_GetById_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetById'
type MockReceptionRepo_GetById_Call struct {
	*mock.Call
}

// GetById is a helper method to define mock.On call
//   - ctx
//   - id
func (_e *MockReceptionRepo_Expecter) GetById(ctx interface{}, id interface{}) *MockReceptionRepo_GetById_Call {
	return &MockReceptionRepo_GetById_Call{Call: _e.mock.On("GetById", ctx, id)}
}

func (_c *MockReceptionRepo_GetById_Call) Run(run func(ctx context.Context, id string)) *MockReceptionRepo_GetById_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockReceptionRepo_GetById_Call) Return(reception *entity.Reception, err error) *MockReceptionRepo_GetById_Call {
	_c.Call.Return(reception, err)
	return _c
}

func (_c *MockReceptionRepo_GetById_Call) RunAndReturn(run func(ctx context.Context, id string) (*entity.Reception, error)) *MockReceptionRepo_GetById_Call {
	_c.Call.Return(run)
	return _c
}

// GetByPvzId provides a mock function for the type MockReceptionRepo
func (_mock *MockReceptionRepo) GetByPvzId(ctx context.Context, pvzId string) ([]entity.Reception, error) {
	ret := _mock.Called(ctx, pvzId)

	if len(ret) == 0 {
		panic("no return value specified for GetByPvzId")
	}

	var r0 []entity.Reception
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) ([]entity.Reception, error)); ok {
		return returnFunc(ctx, pvzId)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) []entity.Reception); ok {
		r0 = returnFunc(ctx, pvzId)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]entity.Reception)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, pvzId)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockReceptionRepo_GetByPvzId_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByPvzId'
type MockReceptionRepo_GetByPvzId_Call struct {
	*mock.Call
}

// GetByPvzId is a helper method to define mock.On call
//   - ctx
//   - pvzId
func (_e *MockReceptionRepo_Expecter) GetByPvzId(ctx interface{}, pvzId interface{}) *MockReceptionRepo_GetByPvzId_Call {
	return &MockReceptionRepo_GetByPvzId_Call{Call: _e.mock.On("GetByPvzId", ctx, pvzId)}
}

func (_c *MockReceptionRepo_GetByPvzId_Call) Run(run func(ctx context.Context, pvzId string)) *MockReceptionRepo_GetByPvzId_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockReceptionRepo_GetByPvzId_Call) Return(receptions []entity.Reception, err error) *MockReceptionRepo_GetByPvzId_Call {
	_c.Call.Return(receptions, err)
	return _c
}

func (_c *MockReceptionRepo_GetByPvzId_Call) RunAndReturn(run func(ctx context.Context, pvzId string) ([]entity.Reception, error)) *MockReceptionRepo_GetByPvzId_Call {
	_c.Call.Return(run)
	return _c
}

// GetByPvzIdWithStatus provides a mock function for the type MockReceptionRepo
func (_mock *MockReceptionRepo) GetByPvzIdWithStatus(ctx context.Context, pvzId string, status entity.ReceptionStatus) ([]entity.Reception, error) {
	ret := _mock.Called(ctx, pvzId, status)

	if len(ret) == 0 {
		panic("no return value specified for GetByPvzIdWithStatus")
	}

	var r0 []entity.Reception
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, entity.ReceptionStatus) ([]entity.Reception, error)); ok {
		return returnFunc(ctx, pvzId, status)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, entity.ReceptionStatus) []entity.Reception); ok {
		r0 = returnFunc(ctx, pvzId, status)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]entity.Reception)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, entity.ReceptionStatus) error); ok {
		r1 = returnFunc(ctx, pvzId, status)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockReceptionRepo_GetByPvzIdWithStatus_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByPvzIdWithStatus'
type MockReceptionRepo_GetByPvzIdWithStatus_Call struct {
	*mock.Call
}

// GetByPvzIdWithStatus is a helper method to define mock.On call
//   - ctx
//   - pvzId
//   - status
func (_e *MockReceptionRepo_Expecter) GetByPvzIdWithStatus(ctx interface{}, pvzId interface{}, status interface{}) *MockReceptionRepo_GetByPvzIdWithStatus_Call {
	return &MockReceptionRepo_GetByPvzIdWithStatus_Call{Call: _e.mock.On("GetByPvzIdWithStatus", ctx, pvzId, status)}
}

func (_c *MockReceptionRepo_GetByPvzIdWithStatus_Call) Run(run func(ctx context.Context, pvzId string, status entity.ReceptionStatus)) *MockReceptionRepo_GetByPvzIdWithStatus_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(entity.ReceptionStatus))
	})
	return _c
}

func (_c *MockReceptionRepo_GetByPvzIdWithStatus_Call) Return(receptions []entity.Reception, err error) *MockReceptionRepo_GetByPvzIdWithStatus_Call {
	_c.Call.Return(receptions, err)
	return _c
}

func (_c *MockReceptionRepo_GetByPvzIdWithStatus_Call) RunAndReturn(run func(ctx context.Context, pvzId string, status entity.ReceptionStatus) ([]entity.Reception, error)) *MockReceptionRepo_GetByPvzIdWithStatus_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateStatus provides a mock function for the type MockReceptionRepo
func (_mock *MockReceptionRepo) UpdateStatus(ctx context.Context, id string, status entity.ReceptionStatus) error {
	ret := _mock.Called(ctx, id, status)

	if len(ret) == 0 {
		panic("no return value specified for UpdateStatus")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, entity.ReceptionStatus) error); ok {
		r0 = returnFunc(ctx, id, status)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockReceptionRepo_UpdateStatus_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateStatus'
type MockReceptionRepo_UpdateStatus_Call struct {
	*mock.Call
}

// UpdateStatus is a helper method to define mock.On call
//   - ctx
//   - id
//   - status
func (_e *MockReceptionRepo_Expecter) UpdateStatus(ctx interface{}, id interface{}, status interface{}) *MockReceptionRepo_UpdateStatus_Call {
	return &MockReceptionRepo_UpdateStatus_Call{Call: _e.mock.On("UpdateStatus", ctx, id, status)}
}

func (_c *MockReceptionRepo_UpdateStatus_Call) Run(run func(ctx context.Context, id string, status entity.ReceptionStatus)) *MockReceptionRepo_UpdateStatus_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(entity.ReceptionStatus))
	})
	return _c
}

func (_c *MockReceptionRepo_UpdateStatus_Call) Return(err error) *MockReceptionRepo_UpdateStatus_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockReceptionRepo_UpdateStatus_Call) RunAndReturn(run func(ctx context.Context, id string, status entity.ReceptionStatus) error) *MockReceptionRepo_UpdateStatus_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockProductRepo creates a new instance of MockProductRepo. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockProductRepo(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockProductRepo {
	mock := &MockProductRepo{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockProductRepo is an autogenerated mock type for the ProductRepo type
type MockProductRepo struct {
	mock.Mock
}

type MockProductRepo_Expecter struct {
	mock *mock.Mock
}

func (_m *MockProductRepo) EXPECT() *MockProductRepo_Expecter {
	return &MockProductRepo_Expecter{mock: &_m.Mock}
}

// Create provides a mock function for the type MockProductRepo
func (_mock *MockProductRepo) Create(ctx context.Context, receptionId string, productType entity.ProductType) (*entity.Product, error) {
	ret := _mock.Called(ctx, receptionId, productType)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 *entity.Product
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, entity.ProductType) (*entity.Product, error)); ok {
		return returnFunc(ctx, receptionId, productType)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, entity.ProductType) *entity.Product); ok {
		r0 = returnFunc(ctx, receptionId, productType)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.Product)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, entity.ProductType) error); ok {
		r1 = returnFunc(ctx, receptionId, productType)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockProductRepo_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockProductRepo_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx
//   - receptionId
//   - productType
func (_e *MockProductRepo_Expecter) Create(ctx interface{}, receptionId interface{}, productType interface{}) *MockProductRepo_Create_Call {
	return &MockProductRepo_Create_Call{Call: _e.mock.On("Create", ctx, receptionId, productType)}
}

func (_c *MockProductRepo_Create_Call) Run(run func(ctx context.Context, receptionId string, productType entity.ProductType)) *MockProductRepo_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(entity.ProductType))
	})
	return _c
}

func (_c *MockProductRepo_Create_Call) Return(product *entity.Product, err error) *MockProductRepo_Create_Call {
	_c.Call.Return(product, err)
	return _c
}

func (_c *MockProductRepo_Create_Call) RunAndReturn(run func(ctx context.Context, receptionId string, productType entity.ProductType) (*entity.Product, error)) *MockProductRepo_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function for the type MockProductRepo
func (_mock *MockProductRepo) Delete(ctx context.Context, id string) error {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = returnFunc(ctx, id)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockProductRepo_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type MockProductRepo_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx
//   - id
func (_e *MockProductRepo_Expecter) Delete(ctx interface{}, id interface{}) *MockProductRepo_Delete_Call {
	return &MockProductRepo_Delete_Call{Call: _e.mock.On("Delete", ctx, id)}
}

func (_c *MockProductRepo_Delete_Call) Run(run func(ctx context.Context, id string)) *MockProductRepo_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockProductRepo_Delete_Call) Return(err error) *MockProductRepo_Delete_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockProductRepo_Delete_Call) RunAndReturn(run func(ctx context.Context, id string) error) *MockProductRepo_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// GetByReceptionId provides a mock function for the type MockProductRepo
func (_mock *MockProductRepo) GetByReceptionId(ctx context.Context, receptionId string) ([]entity.Product, error) {
	ret := _mock.Called(ctx, receptionId)

	if len(ret) == 0 {
		panic("no return value specified for GetByReceptionId")
	}

	var r0 []entity.Product
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) ([]entity.Product, error)); ok {
		return returnFunc(ctx, receptionId)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) []entity.Product); ok {
		r0 = returnFunc(ctx, receptionId)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]entity.Product)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, receptionId)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockProductRepo_GetByReceptionId_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByReceptionId'
type MockProductRepo_GetByReceptionId_Call struct {
	*mock.Call
}

// GetByReceptionId is a helper method to define mock.On call
//   - ctx
//   - receptionId
func (_e *MockProductRepo_Expecter) GetByReceptionId(ctx interface{}, receptionId interface{}) *MockProductRepo_GetByReceptionId_Call {
	return &MockProductRepo_GetByReceptionId_Call{Call: _e.mock.On("GetByReceptionId", ctx, receptionId)}
}

func (_c *MockProductRepo_GetByReceptionId_Call) Run(run func(ctx context.Context, receptionId string)) *MockProductRepo_GetByReceptionId_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockProductRepo_GetByReceptionId_Call) Return(products []entity.Product, err error) *MockProductRepo_GetByReceptionId_Call {
	_c.Call.Return(products, err)
	return _c
}

func (_c *MockProductRepo_GetByReceptionId_Call) RunAndReturn(run func(ctx context.Context, receptionId string) ([]entity.Product, error)) *MockProductRepo_GetByReceptionId_Call {
	_c.Call.Return(run)
	return _c
}

// GetLastInReception provides a mock function for the type MockProductRepo
func (_mock *MockProductRepo) GetLastInReception(ctx context.Context, receptionId string) (*entity.Product, error) {
	ret := _mock.Called(ctx, receptionId)

	if len(ret) == 0 {
		panic("no return value specified for GetLastInReception")
	}

	var r0 *entity.Product
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*entity.Product, error)); ok {
		return returnFunc(ctx, receptionId)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *entity.Product); ok {
		r0 = returnFunc(ctx, receptionId)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.Product)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, receptionId)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockProductRepo_GetLastInReception_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetLastInReception'
type MockProductRepo_GetLastInReception_Call struct {
	*mock.Call
}

// GetLastInReception is a helper method to define mock.On call
//   - ctx
//   - receptionId
func (_e *MockProductRepo_Expecter) GetLastInReception(ctx interface{}, receptionId interface{}) *MockProductRepo_GetLastInReception_Call {
	return &MockProductRepo_GetLastInReception_Call{Call: _e.mock.On("GetLastInReception", ctx, receptionId)}
}

func (_c *MockProductRepo_GetLastInReception_Call) Run(run func(ctx context.Context, receptionId string)) *MockProductRepo_GetLastInReception_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockProductRepo_GetLastInReception_Call) Return(product *entity.Product, err error) *MockProductRepo_GetLastInReception_Call {
	_c.Call.Return(product, err)
	return _c
}

func (_c *MockProductRepo_GetLastInReception_Call) RunAndReturn(run func(ctx context.Context, receptionId string) (*entity.Product, error)) *MockProductRepo_GetLastInReception_Call {
	_c.Call.Return(run)
	return _c
}
